---
- name: Provision Image Jenkins on Centos7 to build
  hosts: packer-jenkins
  become: true
  roles:
    - role: geerlingguy.repo-epel
    - role: geerlingguy.pip
    - role: dinivas.jenkins
      jenkins_plugin_timeout: 90
      jenkins_plugins:
        - git
        - sonar
        - blueocean
        - ssh-agent
        - pipeline-maven
        - keycloak